### ISSUE TITLE
data carpentry intro R typos

### ISSUE THREAD

**Issue by byandell** [kbroman/datacarpentry_R_2016-08-23#1]
Karl,
In document
https://github.com/kbroman/datacarpentry_R_2016-08-23/blob/gh-pages/01-intro-to-R.Rmd
there are two bugs.
1. I found a bug in the **Data Frames** section:
Use tail() to view the **first** few rows.
tail(surveys)
should read "last few rows"
1. Also, Shane Simonett in Attie's lab found that the link to Google's style sheet in the **Object Names** section is broken. It should be
   https://google.github.io/styleguide/Rguide.xml

Cheers, Brian

**Comment by kbroman** [comment]
Fixed, thanks!
